---
name: Update development documentation

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths:
    - README.md
    - Taskfile.yaml
    - .github/workflows/example.yaml

permissions:
  contents: write

jobs:
  docs:
    name: Update development documentation section in README.md
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get development tasks
      id: tasks
      run: |
        { echo "tasks<<EOF"; task; echo "EOF"; } >> "$GITHUB_OUTPUT"
    - name: Update development tasks section
      uses: alistaircol/update-markdown-action@v0.0.2
      with:
        file: README.md
        delimiter-open: <!-- start-task-list -->
        delimiter-close: <!-- end-task-list -->
        content: |
          > **Note**
          > This section of the `README.md` is updated using this action in an [example workflow](https://github.com/alistaircol/update-markdown-action/blob/main/.github/workflows/example.yaml#L33)!

          ```
          ${{ steps.tasks.outputs.tasks }}
          ```
    - name: Commit updated README.md if applicable
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_email: ${github.actor}@users.noreply.github.com
        commit_message: |
          chore(docs): Update GitHub action documentation section in README.md
        commit_options: --no-verify
