---
name: Unit Test

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths:
    - index.js
    - lib/**/*.js
    - tests/**/*.js
    - .github/workflows/test.yaml

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
