---
name: Update action documentation

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths:
    - README.md
    - action.yml
    - .github/workflows/update-action-docs.yaml

permissions:
  contents: write

jobs:
  docs:
    name: Update GitHub action documentation section in README.md
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Update README.md with GitHub action documentation
      uses: npalm/action-docs-action@v1.4.0
      with:
        readme: README.md
        actionFile: action.yml
        tocLevel: 2
    - name: Update README.md TOC
      uses: technote-space/toc-generator@v4
      with:
        TOC_TITLE: ""
        TARGET_PATHS: README.md
        COMMIT_MESSAGE: |
          chore(docs): Update README table of contents
    - name: Commit updated README.md if applicable
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_email: ${github.actor}@users.noreply.github.com
        commit_message: |
          chore(docs): Update GitHub action documentation section in README.md
        commit_options: --no-verify
